# Generated by Django 5.1.5 on 2025-04-13 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genra_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.FileField(blank=True, upload_to='submissions/lyrics')),
                ('music', models.FileField(blank=True, upload_to='submissions/music')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_contact', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(upload_to='artist/profile_pics')),
                ('description', models.TextField()),
                ('No_of_songs', models.IntegerField(default=0)),
                ('Links', models.TextField()),
                ('Creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Genra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genra_artists', to='redpillmusicapp.genra')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_artist', to='redpillmusicapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='default_images')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redpillmusicapp.imagetype')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='songs')),
                ('embeded_link', models.TextField()),
                ('Song_name', models.CharField(max_length=100)),
                ('Lyrics', models.FileField(blank=True, null=True, upload_to='lyrics')),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='redpillmusicapp.artist')),
                ('Genra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genra_songs', to='redpillmusicapp.genra')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redpillmusicapp.song')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redpillmusicapp.song')),
            ],
        ),
    ]
